name: Continuous Integration

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v3.0
        with: 
          prettier_options: --write **/*.{js,css,yaml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_PHP: true
          VALIDATE_HTML: true
          