name: Prettier

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify
        uses: creyD/prettier_action@v3.0
        with: 
          prettier_options: --write **/*.{js,css,yaml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
