title: default
'@extends': default

form:
  fields:
    tabs:
      fields:
        options:
          fields:
            publishing:
              fields:

                header.page_title:
                  type: text
                  label: Page Title

                header.meta_description:
                  type: text
                  label: Meta Description

                header.meta_image:
                  label: Meta Image
                  type: pagemediaselect

            theme:
              type: section
              title: Theme
              underline: true
              fields:

                header.color_bg:
                  label: color_bg
                  type: colorpicker

                header.color_fg:
                  label: color_fg
                  type: colorpicker

                header.color_hl:
                  label: color_hl
                  type: colorpicker

                header.color_btn_bg:
                  label: color_btn_bg
                  type: colorpicker
                  
                header.color_btn_fg:
                  label: color_btn_fg
                  type: colorpicker