title: default
"@extends": default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.display_title:
              ordering@: header.title
              type: text
              style: vertical
              label: Display Title

        options:
          fields:
            publishing:
              fields:
                header.meta_title:
                  type: text
                  label: Meta Title

                header.meta_description:
                  type: text
                  label: Meta Description

                header.meta_image:
                  label: Meta Image
                  type: pagemediaselect
