title: default
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            content:
              label: Content

        options:
          fields:
            publishing:
              fields:
                header.page_title:
                  type: text
                  label: Page Title

                header.page_description:
                  type: text
                  label: Page Description

                header.page_image:
                  label: Page Image
                  type: pagemediaselect
