title: product
"@extends": default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            content:
              ordering@: header.short_description
              label: Description

            header.product:
              type: section
              title: Product
              underline: true

            header.id:
              type: text
              label: id
              help: Product's unique ID
              validate:
                required: true

            header.name:
              type: text
              label: name
              help: Product's name
              validate:
                required: true

            header.price:
              type: text
              label: price
              help: Product's price. You must use a . as decimal separator.
              validate:
                type: number
                min: 0
                required: true

            header.main_image:
              type: pagemediaselect
              label: main_image
              help: Main image representing the product (will also appear in the cart).
              accept:
                - jpg

            header.main_image_alt:
              type: text
              label: main_image_alt

            header.short_description:
              type: text
              label: short_description
              help: The Product's description showing in the cart.
               
            header.section_custom_fields:
              type: section
              title: Custom Fields
              underline: true

            header.custom_fields:
              name: custom_fields
              type: list
              style: vertical
              label: custom_fields
              fields:
                .name:
                  type: text
                  label: Name
                .type:
                  type: select
                  label: Type
                  options:
                    select: select
                    input: input
                    textarea: textarea
                    checkbox: checkbox
                .options:
                  type: text
                  label: options
                  markdown: true
                  description: "A list of | separeted values to be used by the SELECT field type. ex: `S|M|L`"
            
            # header.initial_stock:
            #   type: section
            #   title: Initial Stock
            #   markdown: true
            #   underline: true

            # header.variants:
            #   name: variants
            #   type: list
            #   style: vertical
            #   label: Variants
            #   fields:
            #     .options:
            #       type: selectize
            #       label: Options
            #       validate:
            #           type: commalist
            #     .initial_stock:
            #       type: text
            #       label: Initial Stock
            #       description: Initial stock should only be used when adding a new product to the store and using the Snipcart JSON crawler.
            #       validate:
            #         type: number
            #         min: 0

            header.shipping:
              type: section
              title: Shipping
              underline: true

            header.weight:
              type: text
              label: "weight (g)"
              validate:
                type: number
                min: 0

            header.width:
              type: text
              label: "width (cm)"
              validate:
                type: number
                min: 0

            header.height:
              type: text
              label: "height (cm)"
              validate:
                type: number
                min: 0

            header.gallery:
              type: section
              title: Gallery
              underline: true

            header.gallery_images:
              name: gallery_images
              type: list
              style: vertical
              label: gallery_images

              fields:
                .image:
                  type: pagemediaselect
                  label: image
                  accept:
                    - jpg

                .image_alt:
                  type: text
                  label: image_alt

            header.section_misc:
              type: section
              title: Misc
              underline: true

            header.stackable:
              type: toggle
              label: Stackable
              highlight: 1
              default: 0
              options:
                1: PLUGIN_ADMIN.ENABLED
                0: PLUGIN_ADMIN.DISABLED
              validate:
                type: bool

            header.digital_good_guid:
              type: text
              label: Digital Good GUID
