title: product
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            header.display_title:
              ordering@: header.title
              type: text
              style: vertical
              label: Display Title

            header.section_product:
              type: section
              title: Product
              underline: true

            header.name:
              type: text
              label: Name
              help: Product's name to be used by Snipcart.
              validate:
                required: true

            header.id:
              type: text
              label: Id / SKU
              help: Product's unique ID to be used by Snipcart.
              validate:
                required: true

            header.price:
              type: text
              label: Price
              help: Product's price, using "." as decimal separator.
              validate:
                type: number
                min: 0
                required: true

            header.image:
              type: pagemediaselect
              label: Image
              help: The main image of the product (must be a jpg).
              accept:
                - jpg

            header.description:
              type: text
              label: Description
              help: A short description to appear inside the cart.

            header.taxable:
              type: toggle
              label: Taxable
              highlight: 1
              default: 1
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
              validate:
                type: bool

            header.section_shipping:
              type: section
              title: Shipping
              underline: true

            header.shippable:
              type: toggle
              label: Shippable
              highlight: 1
              default: 1
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
              validate:
                type: bool

            header.weight:
              type: text
              label: Weight (g)
              validate:
                type: number
                min: 0

            header.length:
              type: text
              label: Length (cm)
              validate:
                type: number
                min: 0
                
            header.width:
              type: text
              label: Width (cm)
              validate:
                type: number
                min: 0

            header.height:
              type: text
              label: Height (cm)
              validate:
                type: number
                min: 0
               
            header.section_custom_fields:
              type: section
              title: Custom Fields
              underline: true

            header.custom_fields:
              name: custom_fields
              type: list
              style: vertical
              label: custom_fields
              fields:
                .name:
                  type: text
                  label: Name
                .type:
                  type: select
                  label: Type
                  options:
                    select: select
                    input: input
                    textarea: textarea
                    checkbox: checkbox
                .options:
                  type: text
                  label: Options
                  markdown: true
                  description: "A list of | separeted values to be used by the SELECT field type. ex: `S|M|L`"

            header.section_gallery:
              type: section
              title: Gallery
              underline: true

            header.gallery_images:
              name: gallery_images
              type: list
              style: vertical
              label: gallery_images

              fields:
                .image:
                  type: pagemediaselect
                  label: image
                  accept:
                    - jpg

                .image_alt:
                  type: text
                  label: image_alt

            header.section_misc:
              type: section
              title: Misc
              underline: true

            header.related:
              type: toggle
              label: Related
              highlight: 1
              default: 1
              options:
                0: None
                1: Random
                3: As Specified

            header.stackable:
              type: toggle
              label: Stackable
              highlight: 1
              default: 0
              options:
                1: Auto
                0: Never
              validate:
                type: bool

            header.file_guid:
              type: text
              label: File GUID
              description: To be used if your product is related to a digital good uploaded via our dashboard. You will find the file GUID in the dashboard once the digital good is created.
