title: product
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            header.id:
              type: text
              label: ID

            header.name:
              type: text
              label: Name

            header.price:
              type: text
              label: Price
              validate:
                type: number
                min: 0

            header.description:
              type: text
              label: Description

            header.image:
              label: Image
              type: pagemediaselect
              accept:
                - jpg
              
