title: product
"@extends": default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.id:
              type: text
              label: id

            header.name:
              type: text
              label: name

            header.price:
              type: text
              label: price
              validate:
                type: number
                min: 0

            header.description:
              type: text
              label: description

            header.image:
              type: pagemediaselect
              label: main_image
              accept:
                - jpg

            header.images:
              name: images
              type: list
              style: vertical
              label: images
              fields:
                .image:
                  label: image
                  type: pagemediaselect
                  accept:
                    - jpg
                .alt:
                  type: text
                  label: alt
